import { Produto } from "../produtos/produto";

export const listaDeProdutos: Produto[] = [
    {
        id: 1,
        esporte: 'basquete',
        marca: 'nike',
        tipoCamisa: 'clube',
        categoria: "chaveiro",
        nome: "Chaveiro Real Madrid",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do Real Madrid, temporada 2023/24.",
        preco: 349.90,
        pais: "Espanha"
    },
    {
        id: 2,
        esporte: 'basquete',
        marca: 'puma',
        tipoCamisa: 'selecao',
        categoria: "camisa",
        nome: "Camisa Real Madrid",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do FC Barcelona, temporada 2023/24.",
        preco: 329.90,
        pais: "Espanha"
    },
    {
        id: 3,
        esporte: 'basquete',
        marca: 'puma',
        tipoCamisa: 'clube',
        categoria: "camisa",
        nome: "Camisa Manchester United 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do Manchester United, temporada 2023/24.",
        preco: 359.90,
        pais: "Inglaterra"
    },
    {
        id: 4,
        esporte: 'basquete',
        marca: 'puma',
        tipoCamisa: 'clube',
        categoria: "camisa",
        nome: "Camisa Juventus 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial da Juventus, temporada 2023/24.",
        preco: 339.90,
        pais: "Itália"
    },
    {
        id: 5,
        esporte: 'americano',
        marca: 'puma',
        tipoCamisa: 'clube',
        categoria: "camisa",
        nome: "Camisa Paris Saint-Germain 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do PSG, temporada 2023/24.",
        preco: 349.90,
        pais: "França"
    },
    {
        id: 6,
        esporte: 'americano',
        marca: 'puma',
        tipoCamisa: 'clube',
        categoria: "camisa",
        nome: "Camisa Bayern de Munique 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do Bayern de Munique, temporada 2023/24.",
        preco: 329.90,
        pais: "Alemanha"
    },
    {
        id: 7,
        esporte: 'americano',
        marca: 'puma',
        tipoCamisa: 'clube',
        categoria: "camisa",
        nome: "Camisa Arsenal 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do Arsenal FC, temporada 2023/24.",
        preco: 319.90,
        pais: "Inglaterra"
    },
    {
        id: 8,
        esporte: 'americano',
        marca: 'puma',
        tipoCamisa: 'clube',
        categoria: "camisa",
        nome: "Camisa Milan 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do AC Milan, temporada 2023/24.",
        preco: 339.90,
        pais: "Itália"
    },
    {
        id: 9,
        esporte: 'futebol',
        marca: 'puma',
        tipoCamisa: 'clube',
        categoria: "camisa",
        nome: "Camisa Corinthians 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do Corinthians, temporada 2023.",
        preco: 299.90,
        pais: "Brasil"
    },
    {
        id: 10,
        esporte: 'futebol',
        marca: 'puma',
        tipoCamisa: 'clube',
        categoria: "camisa",
        nome: "Camisa Flamengo 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do Flamengo, temporada 2023.",
        preco: 309.90,
        pais: "Brasil"
    },
    {
        id: 11,
        esporte: 'futebol',
        marca: 'nike',
        tipoCamisa: 'selecao',
        categoria: "camisa",
        nome: "Camisa Seleção Brasil 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial da Seleção Brasileira, temporada 2023/24.",
        preco: 379.90,
        pais: "Brasil"
    },
    {
        id: 12,
        esporte: 'futebol',
        marca: 'adidas',
        tipoCamisa: 'selecao',
        categoria: "camisa",
        nome: "Camisa Seleção Alemanha 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial da Seleção Alemã, temporada 2023/24.",
        preco: 369.90,
        pais: "Alemanha"
    },
    {
        id: 13,
        esporte: 'futebol',
        marca: 'nike',
        tipoCamisa: 'clube',
        categoria: "camisa",
        nome: "Camisa Chelsea 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do Chelsea FC, temporada 2023/24.",
        preco: 349.90,
        pais: "Inglaterra"
    },
    {
        id: 14,
        esporte: 'futebol',
        marca: 'puma',
        tipoCamisa: 'selecao',
        categoria: "camisa",
        nome: "Camisa Seleção Itália 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial da Seleção Italiana, temporada 2023/24.",
        preco: 359.90,
        pais: "Itália"
    },
    {
        id: 15,
        esporte: 'futebol',
        marca: 'adidas',
        tipoCamisa: 'clube',
        categoria: "camisa",
        nome: "Camisa Real Sociedad 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do Real Sociedad, temporada 2023/24.",
        preco: 329.90,
        pais: "Espanha"
    },
    {
        id: 16,
        esporte: 'futebol',
        marca: 'nike',
        tipoCamisa: 'selecao',
        categoria: "camisa",
        nome: "Camisa Seleção França 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial da Seleção Francesa, temporada 2023/24.",
        preco: 379.90,
        pais: "França"
    },
    {
        id: 17,
        esporte: 'futebol',
        marca: 'adidas',
        tipoCamisa: 'clube',
        categoria: "camisa",
        nome: "Camisa Ajax 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do Ajax, temporada 2023/24.",
        preco: 339.90,
        pais: "Holanda"
    },
    {
        id: 18,
        esporte: 'futebol',
        marca: 'umbro',
        tipoCamisa: 'clube',
        categoria: "camisa",
        nome: "Camisa West Ham 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do West Ham United, temporada 2023/24.",
        preco: 319.90,
        pais: "Inglaterra"
    },
    {
        id: 19,
        esporte: 'futebol',
        marca: 'new balance',
        tipoCamisa: 'clube',
        categoria: "camisa",
        nome: "Camisa Porto 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial do FC Porto, temporada 2023/24.",
        preco: 329.90,
        pais: "Portugal"
    },
    {
        id: 20,
        esporte: 'futebol',
        marca: 'adidas',
        tipoCamisa: 'selecao',
        categoria: "camisa",
        nome: "Camisa Seleção Argentina 2023",
        imagem: "/wireframe.png",
        descricao: "Camisa oficial da Seleção Argentina, temporada 2023/24.",
        preco: 369.90,
        pais: "Argentina"
    }
];
